name: Publish Helm Chart
on:
  push:
    branches: [main]
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Helm
        uses: azure/setup-helm@v3
        with:
          version: v3.12.0
      - name: Package Helm Chart
        run: |
          helm package ./mychart
      - name: Publish to GitHub Pages
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git fetch origin gh-pages
          git checkout gh-pages
          mv mychart-*.tgz .
          helm repo index . --url https://BarakZak.github.io/helm-repo/
          git add .
          git commit -m "Update Helm chart"
          git push origin gh-pages